"""empty message

Revision ID: 1fecfc5d1f40
Revises: c907502de486
Create Date: 2021-01-26 19:22:41.900668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fecfc5d1f40'
down_revision = 'c907502de486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointment', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.add_column('appointment', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('appointment', sa.Column('description', sa.String(length=64), nullable=True))
    op.add_column('appointment', sa.Column('phone', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment', 'admin', ['admin_id'], ['id'])
    op.drop_column('appointment', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('data', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'phone')
    op.drop_column('appointment', 'description')
    op.drop_column('appointment', 'date')
    op.drop_column('appointment', 'admin_id')
    op.drop_table('admin')
    # ### end Alembic commands ###
