"""empty message

Revision ID: 8fbb3d52ddb7
Revises: a9907f698183
Create Date: 2021-01-31 15:09:08.221037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbb3d52ddb7'
down_revision = 'a9907f698183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'admin_id')
    # ### end Alembic commands ###
