"""empty message

Revision ID: fef1311415d3
Revises: 1fecfc5d1f40
Create Date: 2021-01-27 17:52:47.360528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef1311415d3'
down_revision = '1fecfc5d1f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('pic_path', sa.String(length=512), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('admin', 'password')
    op.drop_column('admin', 'username')
    op.drop_constraint('appointment_admin_id_fkey', 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('appointment_admin_id_fkey', 'appointment', 'admin', ['admin_id'], ['id'])
    op.add_column('admin', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('admin', sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_table('pictures')
    # ### end Alembic commands ###
