"""empty message

Revision ID: 5c5b732a2e7c
Revises: 90cfb87b82b8
Create Date: 2021-01-21 19:36:41.030548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5b732a2e7c'
down_revision = '90cfb87b82b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('phone', sa.Integer(), nullable=True))
    op.drop_constraint('person_phone_number_key', 'person', type_='unique')
    op.create_unique_constraint(None, 'person', ['phone'])
    op.drop_column('person', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'person', type_='unique')
    op.create_unique_constraint('person_phone_number_key', 'person', ['phone_number'])
    op.drop_column('person', 'phone')
    # ### end Alembic commands ###
