"""empty message

Revision ID: 90cfb87b82b8
Revises: 7b0f1e3997ef
Create Date: 2021-01-21 16:43:41.393720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cfb87b82b8'
down_revision = '7b0f1e3997ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nationalities_people',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('nationality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nationality_id'], ['nationality.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'nationality_id')
    )
    op.add_column('person', sa.Column('nationalities', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'nationalities')
    op.drop_table('nationalities_people')
    op.drop_table('nationality')
    # ### end Alembic commands ###
